### ISSUE TITLE
As front end developer, learn how React makes HTTP Request 

### ISSUE THREAD

**Issue by michaelzhao820** [Oseutin/ECE-461L-Team-Placeholder-Course-Project#10]

**Comment by Oseutin** [comment]
Successfully learned

**Comment by Oseutin** [comment]
React itself doesn’t make HTTP requests; developers typically use libraries like Axios or the Fetch API within React components to send requests. These requests are often triggered in lifecycle methods (e.g., useEffect in functional components) to interact with APIs and update the component state.
