### ISSUE TITLE
As DevOp Engineer, decide on method to host application

### ISSUE THREAD

**Issue by michaelzhao820** [Oseutin/ECE-461L-Team-Placeholder-Course-Project#6]

**Comment by Oseutin** [comment]
To host an application, you can use a cloud platform like AWS, Azure, or Heroku, or a web server like Apache or Nginx, to deploy your application files and configure server settings. Alternatively, platforms like Netlify or Vercel offer simplified deployment for static and dynamic web apps with automated workflows.
