### ISSUE TITLE
As DevOps Engineer, learn about how to create a CI/CD pipeline

### ISSUE THREAD

**Issue by michaelzhao820** [Oseutin/ECE-461L-Team-Placeholder-Course-Project#8]

**Comment by Oseutin** [comment]
To create a CI/CD pipeline, you define steps for building, testing, and deploying code in a configuration file (e.g., YAML) specific to your CI/CD tool like GitHub Actions, Jenkins, or GitLab CI. This pipeline automates these processes, triggered by events such as code pushes or pull requests, ensuring reliable and consistent software delivery.
