### ISSUE TITLE
As front end developer, learn how React abstracts away from direct DOM manipulation

### ISSUE THREAD

**Issue by michaelzhao820** [Oseutin/ECE-461L-Team-Placeholder-Course-Project#9]

**Comment by Oseutin** [comment]
Successfully learned

**Comment by Oseutin** [comment]
React abstracts direct DOM manipulation by using a virtual DOM, which efficiently tracks changes and updates only the necessary parts of the real DOM. This ensures optimal performance and a declarative programming model, where developers define UI states and React handles the rendering.
